version: '3.7'

services:
  postgres.bouncecode-cms:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bouncecode
    volumes:
      - postgresql.bouncecode-cms:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432' # temporary
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'

volumes:
  postgresql.bouncecode-cms:
