version: "3.7"

services:
  app:
    build: .
    restart: on-failure
    volumes:
      - ./docs:/usr/src/app/docs
      - ./pages:/usr/src/app/pages
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./scripts:/usr/src/app/scripts
    command: "/bin/sh -c 'yarn dev'"
    ports:
      - 8080:8080
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: bouncecode
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bouncecode
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # temporary
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgresql:
